### ISSUE TITLE
1.12.2-1.0.4 recipe transfer causes not responding

### ISSUE THREAD

**Issue by Radipon** [p455w0rd/JustEnoughEnergistics#5] opened 2019-01-19 23:20 UTC
Attempting to autofill recipes in the AE2 Pattern Terminal causes the client to stop responding.  Using the modpack FTB Stoneblock 2, version 1.2.0, with the only change being an update to JEE 1.12.2-1.0.4 based on information [here](https://github.com/p455w0rd/JustEnoughEnergistics/issues/3)

This occurs whether or not I have the materials on hand. Autofilling with the same recipes to the crafting terminal works fine though.

**Comment by codewarrior0** [comment] 2019-01-21 20:58
May be related to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3909

**Comment by p455w0rd** [comment] 2019-01-21 21:57
dupe of #4

**Closed as completed by p455w0rd** 2019-01-21 21:57 UTC
